abuse/urls.py
from django.urls import path, re_path, include

from . import views
from constants.base import EXTENSION_SLUGS_PATH

app_name = 'abuse'
urlpatterns = [
    path('abuse/reports/', views.ReportList.as_view(), name='report-list'),
    path('abuse/reports/<int:pk>/', views.ReportView.as_view(), name='view-report'),
    re_path(
        rf'^(?P<type_slug>{EXTENSION_SLUGS_PATH})/',
        include(
            [
                path(
                    '<slug:slug>/report/',
                    views.ReportExtensionView.as_view(),
                    name='report-extension',
                ),
                path(
                    '<slug:slug>/<str:version>/<int:rating>/report/',
                    views.ReportRatingView.as_view(),
                    name='report-ratings',
                ),
            ],
        ),
    ),
    # TODO: report user view and URL
]

blender_extensions/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.flatpages import views as flatpages_views
from django.urls import path, include, re_path
from django.views.static import serve
from django.views.generic.base import RedirectView

from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

import blender_id_oauth_client.urls

import common.views.errors

admin.site.enable_nav_sidebar = False
admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    path('oauth/', include(blender_id_oauth_client.urls)),
    path('admin/', include('loginas.urls')),
    path('admin/', admin.site.urls),
    path('', include('ratings.urls')),
    path('', include('extensions.urls')),
    path('', include('abuse.urls')),
    path('', include('users.urls')),
    path('', include('teams.urls')),
    path('', include('reviewers.urls')),
    path('', include('notifications.urls')),
    path('', include('apitokens.urls')),
    path('api/swagger/', RedirectView.as_view(url='/api/v1/swagger/')),
    path('api/v1/', SpectacularAPIView.as_view(), name='schema_v1'),
    path('api/v1/swagger/', SpectacularSwaggerView.as_view(url_name='schema_v1'), name='swagger'),
    # Flatpages
    path('about/', flatpages_views.flatpage, {'url': '/about/'}, name='flatpage-about'),
    re_path(r'^(?P<url>.*/)$', flatpages_views.flatpage),
]
handler400 = common.views.errors.ErrorView.as_view(status=400)
handler403 = common.views.errors.ErrorView.as_view(status=403)
handler404 = common.views.errors.ErrorView.as_view(status=404)
handler500 = common.views.errors.ErrorView.as_view(status=500)

if settings.DEBUG:
    urlpatterns = [
        re_path(
            r'^media/(?P<path>.*)$',
            serve,
            {
                'document_root': settings.MEDIA_ROOT,
            },
        ),
        path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns

teams/urls.py
from django.urls import path

import teams.views

app_name = 'teams'
urlpatterns = [
    path('settings/teams/', teams.views.TeamsView.as_view(), name='list'),
    path(
        'settings/leave-team/<slug:slug>/',
        teams.views.LeaveTeamView.as_view(),
        name='leave-team',
    ),
]

teams/models.py
import logging

from django.contrib.auth import get_user_model
from django.db import models, transaction
from django.urls import reverse

from common.model_mixins import CreatedModifiedMixin
from constants.base import (
    TEAM_ROLE_CHOICES,
    TEAM_ROLE_MANAGER,
    TEAM_ROLE_MEMBER,
)
import utils

User = get_user_model()
logger = logging.getLogger(__name__)


class Team(CreatedModifiedMixin, models.Model):
    slug = models.SlugField(unique=True, null=False, blank=False, editable=True)
    name = models.CharField(max_length=128, null=False, blank=False)
    users = models.ManyToManyField(User, through='TeamsUsers', related_name='teams')

    def clean(self) -> None:
        if not self.slug:
            self.slug = utils.slugify(self.name)
        super().clean()

    def __str__(self) -> str:
        return f'<Team {self.name}>'

    def save(self, *args, **kwargs):
        self.clean()
        return super().save(*args, **kwargs)

    def get_absolute_url(self) -> str:
        return reverse('extensions:by-team', kwargs={'team_slug': self.slug})


class TeamsUsers(CreatedModifiedMixin, models.Model):
    class Meta:
        verbose_name = 'Team member'
        verbose_name_plural = 'Team members'

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='team_users')
    role = models.SmallIntegerField(default=TEAM_ROLE_MEMBER, choices=TEAM_ROLE_CHOICES)
    team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='team_users')

    @property
    def is_manager(self) -> bool:
        return self.role == TEAM_ROLE_MANAGER

    @transaction.atomic
    def delete(self):
        # This runs when a user is leaving a team.
        # If the user had authored an extension, other team members shouldn't have access to it,
        # unless the extension has another maintainer who is still on that team.
        for extension in self.user.extensions.filter(team=self.team).all():
            # assuming small datasets, not optimizing db access
            authors = extension.authors.all()
            has_other_authors_from_the_team = False
            for author in authors:
                if author.pk == self.user.pk:
                    continue
                if self.team in author.teams.all():
                    has_other_authors_from_the_team = True
                    break
            if not has_other_authors_from_the_team:
                extension.team = None
                extension.save(update_fields={'team'})

        return super().delete()

    @property
    def may_leave(self) -> bool:
        nr_of_managers = TeamsUsers.objects.filter(role=TEAM_ROLE_MANAGER, team=self.team).count()
        user_is_manager = (
            TeamsUsers.objects.filter(
                role=TEAM_ROLE_MANAGER,
                team=self.team,
                user=self.user,
            ).first()
            is not None
        )
        if user_is_manager and nr_of_managers < 2:
            return False
        return True

teams/views.py
"""Team pages."""
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.views.generic import ListView
from django.views.generic.detail import DetailView

from extensions.models import Extension
from teams.models import Team, TeamsUsers


class TeamsView(LoginRequiredMixin, ListView):
    model = Team

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['team_memberships'] = (
            self.request.user.team_users.select_related('team').order_by('team__name').all()
        )
        return context


class LeaveTeamView(LoginRequiredMixin, DetailView):
    model = Team
    template_name = 'teams/confirm_leave.html'

    def post(self, request, *args, **kwargs):
        team = self.get_object()
        team_user = TeamsUsers.objects.filter(team=team, user=self.request.user).first()
        if team_user and team_user.may_leave:
            team_user.delete()
        return redirect('teams:list')

    def get_context_data(self, **kwargs):
        team = self.get_object()
        team_user = TeamsUsers.objects.filter(team=team, user=self.request.user).first()
        context = super().get_context_data(**kwargs)
        context['may_leave'] = team_user.may_leave
        context['will_lose_access_to'] = list(
            Extension.objects.authored_by(self.request.user).exclude(
                maintainer__user_id=self.request.user.pk
            )
        )
        return context

teams/templates/teams/confirm_leave.html
{% extends "common/base.html" %}
{% load i18n %}
{% block content %}
  <div class="row">
    <div class="col col-md-8 mx-auto my-4">
      <div class="box">
        <h2>
          {% blocktranslate with team_name=object.name %}Leave team {{ team_name }}?{% endblocktranslate %}
        </h2>
        {% if may_leave %}
        <p>
          {% blocktranslate %}
            If you wish to join the team again in the future, you will need to ask the team manager to add you back.
          {% endblocktranslate %}

          {% if will_lose_access_to %}
          <br>
          {% blocktranslate %}
            You will lose access to all team extensions that were not uploaded by you:
          {% endblocktranslate %}
          <ul>
          {% for extension in will_lose_access_to %}
            <li><a href="{{ extension.get_absolute_url }}">{{ extension }}</a></li>
          {% endfor %}
          </ul>
          {% endif %}
        </p>
        <div class="btn-row-fluid">
          <a href="#" class="btn js-btn-back">
            <i class="i-cancel"></i>
            <span>{% trans 'Cancel' %}</span>
          </a>
          <form method="post">
          {% csrf_token %}
            <button type="submit" class="btn btn-block btn-danger">
              <i class="i-log-out"></i>
              <span>{% trans 'Confirm Leave' %}</span>
            </button>
          </form>
        </div>
        {% else %}
        <p>
        {% trans 'You cannot leave this team because you are the only manager.' %}
        </p>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock content %}

teams/templates/teams/team_list.html
{% extends 'users/settings/base.html' %}
{% block page_title %}Teams{% endblock %}

{% block settings %}
  <h1 class="mb-3">Teams</h1>
  <div class="row">
    <div class="col">
      <p>
        To create a new team or become part of an existing one, please
        <a href="https://projects.blender.org/infrastructure/extensions-website/issues/new?template=.gitea/issue_template/team.yaml" target="_blank">get in touch</a>.
      </p>

      {% if team_memberships %}
        <table class="table table-hover">
          <thead>
            <tr>
              <th class="w-100">
                Name
              </th>
              <th>
                Role
              </th>
              <th>
                Users
              </th>
              <th></th>
            </tr>
          </thead>
          <tbody>
              {% for team_member in team_memberships %}
                {% with team=team_member.team %}
                  <tr>
                    <td>
                      <a class="px-0" href="{{ team.get_absolute_url }}">{{ team.name }}</a>
                    </td>
                    <td>
                      <div class="badge">
                        {{ team_member.get_role_display }}
                      </div>
                    </td>
                    <td class="text-center">
                      <div class="badge">
                        {{ team.team_users.all.count }}
                      </div>
                    </td>
                    <td>
                      <div class="dropdown">
                        <button class="btn btn-link dropdown-toggle js-dropdown-toggle" data-toggle-menu-id="team-{{ team.slug }}">
                          <i class="i-more-vertical"></i>
                        </button>
                        <ul class="dropdown-menu dropdown-menu-right js-dropdown-menu" id="team-{{ team.slug }}">
                          <li>
                            <a class="dropdown-item {% if not team_member.may_leave %}dropdown-item-disabled{% endif %}" href="{% url 'teams:leave-team' slug=team.slug %}">
                              <i class="i-log-out"></i>Leave Team
                            </a>
                          </li>
                        </ul>
                      </div>
                    </td>
                  </tr>
                {% endwith %}
              {% endfor %}
          </tbody>
        </table>
      {% else %}
        <p>
          You are not assigned to any teams yet.
        </p>
      {% endif %}
    </div>
  </div>
{% endblock settings %}