abuse/urls.py
from django.urls import path, re_path, include

from . import views
from constants.base import EXTENSION_SLUGS_PATH

app_name = 'abuse'
urlpatterns = [
    path('abuse/reports/', views.ReportList.as_view(), name='report-list'),
    path('abuse/reports/<int:pk>/', views.ReportView.as_view(), name='view-report'),
    re_path(
        rf'^(?P<type_slug>{EXTENSION_SLUGS_PATH})/',
        include(
            [
                path(
                    '<slug:slug>/report/',
                    views.ReportExtensionView.as_view(),
                    name='report-extension',
                ),
                path(
                    '<slug:slug>/<str:version>/<int:rating>/report/',
                    views.ReportRatingView.as_view(),
                    name='report-ratings',
                ),
            ],
        ),
    ),
    # TODO: report user view and URL
]

blender_extensions/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.flatpages import views as flatpages_views
from django.urls import path, include, re_path
from django.views.static import serve
from django.views.generic.base import RedirectView

from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

import blender_id_oauth_client.urls

import common.views.errors

admin.site.enable_nav_sidebar = False
admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    path('oauth/', include(blender_id_oauth_client.urls)),
    path('admin/', include('loginas.urls')),
    path('admin/', admin.site.urls),
    path('', include('ratings.urls')),
    path('', include('extensions.urls')),
    path('', include('abuse.urls')),
    path('', include('users.urls')),
    path('', include('teams.urls')),
    path('', include('reviewers.urls')),
    path('', include('notifications.urls')),
    path('', include('apitokens.urls')),
    path('api/swagger/', RedirectView.as_view(url='/api/v1/swagger/')),
    path('api/v1/', SpectacularAPIView.as_view(), name='schema_v1'),
    path('api/v1/swagger/', SpectacularSwaggerView.as_view(url_name='schema_v1'), name='swagger'),
    # Flatpages
    path('about/', flatpages_views.flatpage, {'url': '/about/'}, name='flatpage-about'),
    re_path(r'^(?P<url>.*/)$', flatpages_views.flatpage),
]
handler400 = common.views.errors.ErrorView.as_view(status=400)
handler403 = common.views.errors.ErrorView.as_view(status=403)
handler404 = common.views.errors.ErrorView.as_view(status=404)
handler500 = common.views.errors.ErrorView.as_view(status=500)

if settings.DEBUG:
    urlpatterns = [
        re_path(
            r'^media/(?P<path>.*)$',
            serve,
            {
                'document_root': settings.MEDIA_ROOT,
            },
        ),
        path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns

extensions/urls.py
from django.urls import path, re_path, include, reverse_lazy
from django.views.generic import RedirectView

from constants.base import EXTENSION_SLUGS_PATH
from extensions.views import api, public, submit, manage

app_name = 'extensions'
urlpatterns = [
    path('submit/', submit.UploadFileView.as_view(), name='submit'),
    # TODO: move /accounts pages under its own app when User model is replaced
    path('accounts/extensions/', manage.ManageListView.as_view(), name='manage-list'),
    # FIXME: while there's no profile page, redirect to My Extensions instead
    path(
        'accounts/profile/',
        RedirectView.as_view(url=reverse_lazy('extensions:manage-list'), permanent=False),
    ),
    # API
    path('api/v1/extensions/', api.ExtensionsAPIView.as_view(), name='api'),
    path(
        'api/v1/extensions/<str:extension_id>/versions/new/',
        api.UploadExtensionVersionView.as_view(),
        name='upload-extension-version',
    ),
    # Public pages
    path('', public.HomeView.as_view(), name='home'),
    path('search/', public.SearchView.as_view(), name='search'),
    path('author/<int:user_id>/', public.SearchView.as_view(), name='by-author'),
    path('search/', public.SearchView.as_view(), name='search'),
    path('tag/<slug:tag_slug>/', public.SearchView.as_view(), name='by-tag'),
    path('team/<slug:team_slug>/', public.SearchView.as_view(), name='by-team'),
    re_path(
        rf'^(?P<type_slug>{EXTENSION_SLUGS_PATH})/',
        include(
            [
                path('<slug:slug>/', public.ExtensionDetailView.as_view(), name='detail'),
            ]
        ),
    ),
    re_path(
        rf'^(?P<type_slug>{EXTENSION_SLUGS_PATH})/$',
        public.SearchView.as_view(),
        name='by-type',
    ),
    # Pages for maintainers
    re_path(
        rf'^(?P<type_slug>{EXTENSION_SLUGS_PATH})/',
        include(
            [
                path(
                    '<slug:slug>/draft/',
                    manage.DraftExtensionView.as_view(),
                    name='draft',
                ),
                path(
                    '<slug:slug>/manage/',
                    manage.UpdateExtensionView.as_view(),
                    name='manage',
                ),
                path(
                    '<slug:slug>/delete/',
                    manage.DeleteExtensionView.as_view(),
                    name='delete',
                ),
                path(
                    '<slug:slug>/manage/versions/',
                    manage.ManageVersionsView.as_view(),
                    name='manage-versions',
                ),
                path(
                    '<slug:slug>/manage/versions/new/',
                    manage.NewVersionView.as_view(),
                    name='new-version',
                ),
                path(
                    '<slug:slug>/manage/versions/new/<int:pk>/',
                    manage.NewVersionFinalizeView.as_view(),
                    name='new-version-finalise',
                ),
                path(
                    '<slug:slug>/manage/versions/<int:pk>/delete/',
                    manage.VersionDeleteView.as_view(),
                    name='version-delete',
                ),
                path(
                    '<slug:slug>/manage/versions/<int:pk>/update/',
                    manage.UpdateVersionView.as_view(),
                    name='version-update',
                ),
                path(
                    '<slug:slug>/<version>/download/<filename>',
                    public.extension_version_download,
                    name='version-download',
                ),
                path('<slug:slug>/versions/', manage.VersionsView.as_view(), name='versions'),
            ],
        ),
    ),
]

abuse/models.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.gis.geoip2 import GeoIP2, GeoIP2Exception
from django.core.validators import validate_ipv46_address
from django.db import models
from django.urls import reverse

from extended_choices import Choices
from geoip2.errors import GeoIP2Error

from constants.base import ABUSE_TYPE, ABUSE_TYPE_EXTENSION, ABUSE_TYPE_RATING
from common.model_mixins import CreatedModifiedMixin, TrackChangesMixin
import extensions.fields

User = get_user_model()


class AbuseReport(CreatedModifiedMixin, TrackChangesMixin, models.Model):
    TYPE = ABUSE_TYPE

    REASONS = Choices(
        ('OTHER', 127, 'Other'),
        ('DAMAGE', 1, 'Damages computer and/or data'),
        ('SPAM', 2, 'Creates spam or advertising'),
        ('BROKEN', 3, "Doesn't work, breaks Blender, or slows it down"),
        ('POLICY', 4, 'Hateful, violent, or illegal content'),
        ('DECEPTIVE', 5, "Pretends to be something it's not"),
    )

    STATUSES = Choices(
        ('UNTRIAGED', 1, 'Untriaged'),
        ('DISMISSED', 2, 'Dismissed'),
        ('RESOLVED', 3, 'Resolved'),
    )

    # NULL if the reporter is anonymous.
    # FIXME? make non-null
    reporter = models.ForeignKey(
        User,
        null=True,
        blank=True,
        related_name='abuse_reported',
        on_delete=models.SET_NULL,
    )
    # An abuse report can be for an extension or a user.
    # If user is set then extension should be null.
    # If extension is null then user should be set.
    user = models.ForeignKey(
        User, null=True, related_name='abuse_reports', on_delete=models.CASCADE
    )
    extension = models.ForeignKey(
        'extensions.Extension', blank=True, null=True, on_delete=models.CASCADE
    )
    extension_version = extensions.fields.VersionStringField(max_length=64, null=True, blank=True)
    rating = models.ForeignKey('ratings.Rating', blank=True, null=True, on_delete=models.CASCADE)
    message = models.TextField(blank=True)
    reason = models.PositiveSmallIntegerField(
        default=REASONS.OTHER, choices=REASONS.choices, blank=False, null=False
    )
    version = extensions.fields.VersionStringField(
        max_length=64,
        null=True,
        blank=True,
        help_text=('Version of Blender affected by this report, if applicable.'),
    )
    type = models.PositiveSmallIntegerField(
        default=ABUSE_TYPE_EXTENSION, choices=TYPE.choices, blank=False, null=False
    )

    status = models.PositiveSmallIntegerField(default=STATUSES.UNTRIAGED, choices=STATUSES.choices)
    moderator_note = models.TextField(blank=True, null=True)
    processed_by = models.ForeignKey(
        User,
        null=True,
        related_name='abuse_reports_processed',
        on_delete=models.PROTECT,
    )

    @classmethod
    def lookup_country_code_from_ip(cls, ip):
        try:
            # Early check to avoid initializing GeoIP2 on invalid addresses
            if not ip:
                raise forms.ValidationError('No IP')
            validate_ipv46_address(ip)
            geoip = GeoIP2()
            value = geoip.country_code(ip)
        # Annoyingly, we have to catch both django's GeoIP2Exception (setup
        # issue) and geoip2's GeoIP2Error (lookup issue)
        except (forms.ValidationError, GeoIP2Exception, GeoIP2Error):
            value = ''
        return value

    @property
    def name(self) -> str:
        return self.extension.name if self.extension else self.user

    def __str__(self) -> str:
        return f'Abuse Report for {self.type} {self.name}'

    @classmethod
    def exists(cls, user_id: int, extension_id: int, rating_id: int = None) -> bool:
        if rating_id is None:
            return cls.objects.filter(
                reporter_id=user_id, extension_id=extension_id, type=ABUSE_TYPE_EXTENSION
            ).exists()
        return cls.objects.filter(
            reporter_id=user_id,
            extension_id=extension_id,
            rating_id=rating_id,
            type=ABUSE_TYPE_RATING,
        ).exists()

    def get_absolute_url(self):
        return reverse('abuse:view-report', args=[self.pk])

    def get_admin_url(self):
        return reverse('admin:abuse_abusereport_change', args=[self.pk])

abuse/views.py
import logging

from actstream import action
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.db import transaction
from django.http import Http404, HttpResponseForbidden
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.shortcuts import get_object_or_404, redirect

from .forms import ReportExtensionForm, ReportRatingForm, ResolveReportForm
from constants.activity import Verb
from constants.base import ABUSE_TYPE_EXTENSION, ABUSE_TYPE_RATING
from abuse.models import AbuseReport
from ratings.models import Rating
from extensions.models import Extension, Version
import extensions.views.mixins

log = logging.getLogger(__name__)


class ReportList(
    LoginRequiredMixin,
    UserPassesTestMixin,
    ListView,
):
    model = AbuseReport
    paginate_by = 100

    def test_func(self) -> bool:
        return self.request.user.is_moderator

    def get_queryset(self):
        return AbuseReport.objects.all().order_by('status', '-date_created')

    template_name = 'abuse/abusereport_list.html'


class ReportExtensionView(
    LoginRequiredMixin,
    extensions.views.mixins.ListedExtensionMixin,
    CreateView,
):
    model = AbuseReport
    form_class = ReportExtensionForm

    def get(self, request, *args, **kwargs):
        extension = get_object_or_404(Extension.objects.listed, slug=self.kwargs['slug'])
        report = AbuseReport.objects.filter(
            reporter_id=self.request.user.pk, extension_id=extension.id
        ).first()
        if report is not None:
            return redirect('abuse:view-report', pk=report.pk)
        else:
            return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        """Link newly created rating to latest version and current user."""
        form.instance.reporter = self.request.user
        form.instance.extension = self.extension
        form.instance.extension_version = self.extension.latest_version.version
        form.instance.type = ABUSE_TYPE_EXTENSION
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['extension'] = self.extension
        return context

    def get_success_url(self) -> str:
        return self.object.get_absolute_url()


class ReportRatingView(
    LoginRequiredMixin,
    extensions.views.mixins.ListedExtensionMixin,
    UserPassesTestMixin,
    CreateView,
):
    model = AbuseReport
    form_class = ReportRatingForm

    def test_func(self) -> bool:
        # TODO: best to redirect to existing report or show a friendly message
        return not AbuseReport.exists(
            user_id=self.request.user.pk, extension_id=self.extension.id, rating_id=self.rating.id
        )

    def dispatch(self, *args, **kwargs):

        self.extension = get_object_or_404(Extension.objects.listed, slug=self.kwargs['slug'])

        self.version = get_object_or_404(
            Version,
            version=self.kwargs['version'],
            extension=self.extension,
        )

        self.rating = get_object_or_404(
            Rating,
            extension=self.extension,
            version=self.version,
            id=self.kwargs['rating'],
        )

        return super().dispatch(*args, **kwargs)

    def form_valid(self, form):
        """Link newly created rating to latest version and current user."""
        form.instance.reporter = self.request.user
        form.instance.extension = self.extension
        form.instance.rating = self.rating
        form.instance.extension_version = self.version.version
        form.instance.type = ABUSE_TYPE_RATING
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['extension'] = self.extension
        context['version'] = self.version
        context['rating'] = self.rating
        return context

    def get_success_url(self) -> str:
        return self.object.get_absolute_url()


class ReportView(LoginRequiredMixin, UpdateView):
    model = AbuseReport
    template_name = 'abuse/abusereport_detail.html'

    def get_object(self, *args, **kwargs):
        obj = super().get_object(*args, **kwargs)
        if self.request.user.is_authenticated and (
            obj.reporter_id == self.request.user.pk or self.request.user.is_moderator
        ):
            return obj
        raise Http404()

    def get_form(self):
        return ResolveReportForm(**self.get_form_kwargs(), request=self.request)

    @transaction.atomic
    def form_valid(self, form):
        response = super().form_valid(form)
        if 'dismiss' in form.data:
            verb = Verb.DISMISSED_ABUSE_REPORT
        if 'resolve' in form.data:
            verb = Verb.RESOLVED_ABUSE_REPORT
        action.send(
            self.request.user,
            verb=verb,
            target=form.instance,
        )
        return response

    def post(self, *args, **kwargs):
        if not self.request.user.is_moderator:
            raise HttpResponseForbidden()
        return super().post(*args, **kwargs)

abuse/templates/abuse/abusereport_detail.html
{% extends "common/base.html" %}
{% load i18n common filters %}
{% block page_title %}Abuse Report for {{ object.name }}{% endblock page_title %}


{% block hero %}
{% with latest=extension.latest_version extension=object.extension %}

<div class="hero extension-detail">
  <div class="container">
    <div class="hero-content">
      {% if user_is_moderator %}
      {% block hero_breadcrumbs %}
      <div class="hero-breadcrumbs">
        <a href="{% url 'abuse:report-list' %}">
          <i class="i-chevron-left"></i>
          <span>{% trans 'All Reports' %}</span>
        </a>
      </div>
      {% endblock hero_breadcrumbs %}
      {% endif %}

      <h1>{{ object.get_type_display }} Report</h1>

      <div class="hero-subtitle d-flex">
        {% if extension %}
          <div class="ext-detail-tagline">
            <a href="{{ extension.get_absolute_url }}">{{ extension.name }}</a>
          </div>
          <div class="ext-detail-authors ms-3">
            <a href="{% url 'extensions:by-type' type_slug=extension.type_slug %}">
              {{ extension.get_type_display }}
            </a>

            {% if extension.team %}
              {% with team=extension.team %}
                {% blocktranslate with absolute_url=team.get_absolute_url name=team.name %}
                  by <a href="{{ absolute_url }}" title="{{ name }}">{{ name }}</a>
                {% endblocktranslate %}
              {% endwith %}
            {% elif extension.authors.count %}
              {% trans 'by' %} {% include "extensions/components/authors.html" %}
            {% endif %}
          </div>
        {% else %}
          <div class="ext-detail-tagline">
            Reported user: {{ object.name }}
          </div>
        {% endif %}
      </div>
    </div>

    {% block hero_tabs %}
    <nav class="hero-tabs">
      <span class="ms-auto"></span>

      <div class="btn-row mb-1">
        {% if request.user.is_staff %}
          <a href="{{ object.get_admin_url }}" class="btn btn-admin btn-block">
            <i class="i-edit"></i>
            <span>Edit Report</span>
          </a>
        {% endif %}
      </div>
    </nav>
    {% endblock hero_tabs %}

  </div>
  <div class="hero-overlay"></div>
</div>
{% endwith %}
{% endblock hero %}

{% block content %}
  <div class="mb-3">
    <div class="row">
      <div class="col-md-8">
        {% if object.rating %}
          {% include "ratings/components/rating.html" with rating=object.rating classes="mb-3" %}
        <hr class="my-4">
        {% endif %}
        <h2>Reason</h2>
        <p>"{{ object.get_reason_display }}"</p>
        <h2 class="mt-4 mb-3">Message</h2>
        <div class="card p-3 mx-1 mb-3">
          {% if object.message %}
            {{ object.message|markdown }}
          {% else %}
            <p>No message provided by reporter.</p>
          {% endif %}
          </div>
      </div>
      <div class="col-md-4">
        <div class="card p-3 mx-1 mb-3 ext-detail-info">
          <dl>
            <div class="dl-row">
              <div class="dl-col">
                <dt>Status</dt>
                <dd>{% include "common/components/status.html" %}</dd>
              </div>
              {% if object.processed_by %}
              <div class="dl-col">
                <dt>Processed by</dt>
                <dd>{{ object.processed_by }}</dd>
              </div>
              {% endif %}
            </div>
            {% if extension %}
            <div class="dl-row">
              <div class="dl-col">
                <dt>{{ extension.get_type_display }}</dt>
                <dd>
                  <a href="{{ extension.get_absolute_url }}">
                    {{ extension.name }}
                  </a>
                </dd>
              </div>
            </div>
            {% endif %}
            <div class="dl-row">
              <div class="dl-col">
                <dt>Submitted</dt>
                <dd title="{{ object.date_created|date:'l jS, F Y - H:i' }}">
                  {{ object.date_created|naturaltime_compact }}
                </dd>
              </div>
              <div class="dl-col">
                <dt>by</dt>
                <dd>
                  {% if object.reporter %}
                    <a href="{% url "extensions:by-author" user_id=object.reporter.pk %}">
                      {{ object.reporter }}
                    </a>
                  {% else %}
                    unknown
                  {% endif %}
                </dd>
              </div>
            </div>
          </dl>
        </div>
      </div>
    </div>
  </div>
  {% if user_is_moderator %}
  <div class="col-md-8">
    <form method="post" enctype="multipart/form-data" class="mt-3">
      {% csrf_token %}
      {% with form=form|add_form_classes %}
      <div class="row mb-3">
        <div class="col">
          {% include "common/components/field.html" with field=form.moderator_note placeholder="Add a note..." %}
        </div>
      </div>
      {% endwith %}
      <button type="submit" class="btn btn-primary" name="resolve"><i class="i-check"></i> Resolve</button>
      <button type="submit" class="btn btn-secondary" name="dismiss"><i class="i-trash"></i> Dismiss</button>
    </form>
  </div>
  {% elif object.moderator_note %}
  <h2>Moderator note</h2>
  <p>{{ object.moderator_note }}</p>
  {% endif %}
{% endblock content %}

abuse/templates/abuse/abusereport_form.html
{% extends "extensions/base.html" %}
{% load i18n common %}
{% block page_title %}Report {{ extension.name }}{% endblock page_title %}

{% block content %}
<div class="row">
  <div class="col-md-8 mx-auto">
    <div class="card p-4">
      {% if rating %}
      <h2>Report Review</h2>
      <div class="box-outline p-2 my-3">
        {% include "ratings/components/rating.html" with classes="is-abuse-report" %}
      </div>
      {% else %}
      <h2>Report {{ extension.name }}</h2>
      {% endif %}
      <form method="post" enctype="multipart/form-data" class="mt-3">{% csrf_token %}
        {% with form=form|add_form_classes %}
          {{ form.as_p }}
          {% if form.non_field_errors %}
            <div class="row mt-3">
              <div class="col">
                <div class="invalid-feedback mt-3">
                  {{ form.non_field_errors }}
                </div>
              </div>
            </div>
          {% endif %}

          <button type="submit" class="btn btn-block btn-primary mt-3">
            <span>{% trans 'Submit Report' %}</span>
          </button>

        {% endwith %}
      </form>
    </div>
  </div>
{% endblock content %}

abuse/templates/abuse/abusereport_list.html
{% extends "common/base.html" %}
{% load common i18n humanize filters %}

{% block page_title %}Approval queue{% endblock page_title %}

{% block content %}
<div class="mt-4 row">
  <div class="col">
    <h2 class="mb-3">
      {% blocktranslate %}
      Abuse Reports
      {% endblocktranslate %}
    </h2>
  </div>
</div>

<section class="ext-review-list">
  {% if object_list %}
    <table class="table table-hover">
      <thead>
        <tr>
          <th>{% trans "Type" %}</th>
          <th>{% trans "Extension" %}</th>
          <th></th>
          <th>{% trans "Reporter" %}</th>
          <th>{% trans "Submitted" %}</th>
          <th>{% trans "Status" %}</th>
          <th>{% trans "Process by" %}</th>
        </tr>
      </thead>
      <tbody>
        {% for report in object_list %}
        <tr>
          <td class="ext-review-list-type">{{ report.get_type_display }}</td>
          <td>
            <a href="{{ report.get_absolute_url }}">
              {{ report.extension.name }}
            </a>
          </td>
          <td title="{{ report.rating }}">
            {% if report.rating %}{{ report.rating.text|truncatewords:8 }}{% endif %}
          </td>
          <td>
            <a href="{% url "extensions:by-author" user_id=report.reporter.pk %}">
              {{ report.reporter }}
            </a>
          </td>
          <td title="{{ report.date_created }}">{{ report.date_created|naturaltime_compact }}</td>
          <td>
            <a href="{{ report.get_absolute_url }}" class="text-decoration-none">
              {% include "common/components/status.html" with object=report classes="d-block" %}
            </a>
          </td>
          <td>
          {{ report.processed_by|default:"-" }}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>{% trans "No extensions to review." %}</p>
  {% endif %}
</section>
{{ page_obj|paginator }}
{% endblock content %}