abuse/urls.py
from django.urls import path, re_path, include

from . import views
from constants.base import EXTENSION_SLUGS_PATH

app_name = 'abuse'
urlpatterns = [
    path('abuse/reports/', views.ReportList.as_view(), name='report-list'),
    path('abuse/reports/<int:pk>/', views.ReportView.as_view(), name='view-report'),
    re_path(
        rf'^(?P<type_slug>{EXTENSION_SLUGS_PATH})/',
        include(
            [
                path(
                    '<slug:slug>/report/',
                    views.ReportExtensionView.as_view(),
                    name='report-extension',
                ),
                path(
                    '<slug:slug>/<str:version>/<int:rating>/report/',
                    views.ReportRatingView.as_view(),
                    name='report-ratings',
                ),
            ],
        ),
    ),
    # TODO: report user view and URL
]

blender_extensions/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.flatpages import views as flatpages_views
from django.urls import path, include, re_path
from django.views.static import serve
from django.views.generic.base import RedirectView

from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

import blender_id_oauth_client.urls

import common.views.errors

admin.site.enable_nav_sidebar = False
admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    path('oauth/', include(blender_id_oauth_client.urls)),
    path('admin/', include('loginas.urls')),
    path('admin/', admin.site.urls),
    path('', include('ratings.urls')),
    path('', include('extensions.urls')),
    path('', include('abuse.urls')),
    path('', include('users.urls')),
    path('', include('teams.urls')),
    path('', include('reviewers.urls')),
    path('', include('notifications.urls')),
    path('', include('apitokens.urls')),
    path('api/swagger/', RedirectView.as_view(url='/api/v1/swagger/')),
    path('api/v1/', SpectacularAPIView.as_view(), name='schema_v1'),
    path('api/v1/swagger/', SpectacularSwaggerView.as_view(url_name='schema_v1'), name='swagger'),
    # Flatpages
    path('about/', flatpages_views.flatpage, {'url': '/about/'}, name='flatpage-about'),
    re_path(r'^(?P<url>.*/)$', flatpages_views.flatpage),
]
handler400 = common.views.errors.ErrorView.as_view(status=400)
handler403 = common.views.errors.ErrorView.as_view(status=403)
handler404 = common.views.errors.ErrorView.as_view(status=404)
handler500 = common.views.errors.ErrorView.as_view(status=500)

if settings.DEBUG:
    urlpatterns = [
        re_path(
            r'^media/(?P<path>.*)$',
            serve,
            {
                'document_root': settings.MEDIA_ROOT,
            },
        ),
        path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns

extensions/urls.py
from django.urls import path, re_path, include, reverse_lazy
from django.views.generic import RedirectView

from constants.base import EXTENSION_SLUGS_PATH
from extensions.views import api, public, submit, manage

app_name = 'extensions'
urlpatterns = [
    path('submit/', submit.UploadFileView.as_view(), name='submit'),
    # TODO: move /accounts pages under its own app when User model is replaced
    path('accounts/extensions/', manage.ManageListView.as_view(), name='manage-list'),
    # FIXME: while there's no profile page, redirect to My Extensions instead
    path(
        'accounts/profile/',
        RedirectView.as_view(url=reverse_lazy('extensions:manage-list'), permanent=False),
    ),
    # API
    path('api/v1/extensions/', api.ExtensionsAPIView.as_view(), name='api'),
    path(
        'api/v1/extensions/<str:extension_id>/versions/new/',
        api.UploadExtensionVersionView.as_view(),
        name='upload-extension-version',
    ),
    # Public pages
    path('', public.HomeView.as_view(), name='home'),
    path('search/', public.SearchView.as_view(), name='search'),
    path('author/<int:user_id>/', public.SearchView.as_view(), name='by-author'),
    path('search/', public.SearchView.as_view(), name='search'),
    path('tag/<slug:tag_slug>/', public.SearchView.as_view(), name='by-tag'),
    path('team/<slug:team_slug>/', public.SearchView.as_view(), name='by-team'),
    re_path(
        rf'^(?P<type_slug>{EXTENSION_SLUGS_PATH})/',
        include(
            [
                path('<slug:slug>/', public.ExtensionDetailView.as_view(), name='detail'),
            ]
        ),
    ),
    re_path(
        rf'^(?P<type_slug>{EXTENSION_SLUGS_PATH})/$',
        public.SearchView.as_view(),
        name='by-type',
    ),
    # Pages for maintainers
    re_path(
        rf'^(?P<type_slug>{EXTENSION_SLUGS_PATH})/',
        include(
            [
                path(
                    '<slug:slug>/draft/',
                    manage.DraftExtensionView.as_view(),
                    name='draft',
                ),
                path(
                    '<slug:slug>/manage/',
                    manage.UpdateExtensionView.as_view(),
                    name='manage',
                ),
                path(
                    '<slug:slug>/delete/',
                    manage.DeleteExtensionView.as_view(),
                    name='delete',
                ),
                path(
                    '<slug:slug>/manage/versions/',
                    manage.ManageVersionsView.as_view(),
                    name='manage-versions',
                ),
                path(
                    '<slug:slug>/manage/versions/new/',
                    manage.NewVersionView.as_view(),
                    name='new-version',
                ),
                path(
                    '<slug:slug>/manage/versions/new/<int:pk>/',
                    manage.NewVersionFinalizeView.as_view(),
                    name='new-version-finalise',
                ),
                path(
                    '<slug:slug>/manage/versions/<int:pk>/delete/',
                    manage.VersionDeleteView.as_view(),
                    name='version-delete',
                ),
                path(
                    '<slug:slug>/manage/versions/<int:pk>/update/',
                    manage.UpdateVersionView.as_view(),
                    name='version-update',
                ),
                path(
                    '<slug:slug>/<version>/download/<filename>',
                    public.extension_version_download,
                    name='version-download',
                ),
                path('<slug:slug>/versions/', manage.VersionsView.as_view(), name='versions'),
            ],
        ),
    ),
]

abuse/models.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.gis.geoip2 import GeoIP2, GeoIP2Exception
from django.core.validators import validate_ipv46_address
from django.db import models
from django.urls import reverse

from extended_choices import Choices
from geoip2.errors import GeoIP2Error

from constants.base import ABUSE_TYPE, ABUSE_TYPE_EXTENSION, ABUSE_TYPE_RATING
from common.model_mixins import CreatedModifiedMixin, TrackChangesMixin
import extensions.fields

User = get_user_model()


class AbuseReport(CreatedModifiedMixin, TrackChangesMixin, models.Model):
    TYPE = ABUSE_TYPE

    REASONS = Choices(
        ('OTHER', 127, 'Other'),
        ('DAMAGE', 1, 'Damages computer and/or data'),
        ('SPAM', 2, 'Creates spam or advertising'),
        ('BROKEN', 3, "Doesn't work, breaks Blender, or slows it down"),
        ('POLICY', 4, 'Hateful, violent, or illegal content'),
        ('DECEPTIVE', 5, "Pretends to be something it's not"),
    )

    STATUSES = Choices(
        ('UNTRIAGED', 1, 'Untriaged'),
        ('DISMISSED', 2, 'Dismissed'),
        ('RESOLVED', 3, 'Resolved'),
    )

    # NULL if the reporter is anonymous.
    # FIXME? make non-null
    reporter = models.ForeignKey(
        User,
        null=True,
        blank=True,
        related_name='abuse_reported',
        on_delete=models.SET_NULL,
    )
    # An abuse report can be for an extension or a user.
    # If user is set then extension should be null.
    # If extension is null then user should be set.
    user = models.ForeignKey(
        User, null=True, related_name='abuse_reports', on_delete=models.CASCADE
    )
    extension = models.ForeignKey(
        'extensions.Extension', blank=True, null=True, on_delete=models.CASCADE
    )
    extension_version = extensions.fields.VersionStringField(max_length=64, null=True, blank=True)
    rating = models.ForeignKey('ratings.Rating', blank=True, null=True, on_delete=models.CASCADE)
    message = models.TextField(blank=True)
    reason = models.PositiveSmallIntegerField(
        default=REASONS.OTHER, choices=REASONS.choices, blank=False, null=False
    )
    version = extensions.fields.VersionStringField(
        max_length=64,
        null=True,
        blank=True,
        help_text=('Version of Blender affected by this report, if applicable.'),
    )
    type = models.PositiveSmallIntegerField(
        default=ABUSE_TYPE_EXTENSION, choices=TYPE.choices, blank=False, null=False
    )

    status = models.PositiveSmallIntegerField(default=STATUSES.UNTRIAGED, choices=STATUSES.choices)
    moderator_note = models.TextField(blank=True, null=True)
    processed_by = models.ForeignKey(
        User,
        null=True,
        related_name='abuse_reports_processed',
        on_delete=models.PROTECT,
    )

    @classmethod
    def lookup_country_code_from_ip(cls, ip):
        try:
            # Early check to avoid initializing GeoIP2 on invalid addresses
            if not ip:
                raise forms.ValidationError('No IP')
            validate_ipv46_address(ip)
            geoip = GeoIP2()
            value = geoip.country_code(ip)
        # Annoyingly, we have to catch both django's GeoIP2Exception (setup
        # issue) and geoip2's GeoIP2Error (lookup issue)
        except (forms.ValidationError, GeoIP2Exception, GeoIP2Error):
            value = ''
        return value

    @property
    def name(self) -> str:
        return self.extension.name if self.extension else self.user

    def __str__(self) -> str:
        return f'Abuse Report for {self.type} {self.name}'

    @classmethod
    def exists(cls, user_id: int, extension_id: int, rating_id: int = None) -> bool:
        if rating_id is None:
            return cls.objects.filter(
                reporter_id=user_id, extension_id=extension_id, type=ABUSE_TYPE_EXTENSION
            ).exists()
        return cls.objects.filter(
            reporter_id=user_id,
            extension_id=extension_id,
            rating_id=rating_id,
            type=ABUSE_TYPE_RATING,
        ).exists()

    def get_absolute_url(self):
        return reverse('abuse:view-report', args=[self.pk])

    def get_admin_url(self):
        return reverse('admin:abuse_abusereport_change', args=[self.pk])

extensions/views/mixins.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import get_object_or_404

from extensions.models import Extension
from files.models import File


class OwnsFileMixin(UserPassesTestMixin):
    def dispatch(self, *args, **kwargs):
        self.file = get_object_or_404(File, pk=self.kwargs['pk'])
        self.extension = self._get_extension()
        return super().dispatch(*args, **kwargs)

    def test_func(self) -> bool:
        return self.file.user == self.request.user


class ExtensionQuerysetMixin:
    """Add reusable methods to class-based views handling Extensions."""

    def get_extension_queryset(self):
        """Return queryset with unlisted add-ons for logged in users under certain conditions."""
        if self.request.user.is_staff:
            return Extension.objects.all()
        if self.request.user.is_authenticated:
            return Extension.objects.listed_or_authored_by(self.request.user)
        return Extension.objects.listed


class MaintainedExtensionMixin:
    """Fetch an extension by slug if current user is a maintainer."""

    def dispatch(self, *args, **kwargs):
        self.extension = get_object_or_404(
            Extension.objects.authored_by(self.request.user),
            slug=self.kwargs['slug'],
        )
        return super().dispatch(*args, **kwargs)


class ListedExtensionMixin:
    """Fetch a publicly listed extension by slug in the URL before dispatching the view."""

    def dispatch(self, *args, **kwargs):
        self.extension = get_object_or_404(Extension.objects.listed, slug=self.kwargs['slug'])
        return super().dispatch(*args, **kwargs)


class ExtensionMixin:
    """Fetch an extension by slug in the URL before dispatching the view."""

    def dispatch(self, *args, **kwargs):
        self.extension = get_object_or_404(Extension, slug=self.kwargs['slug'])
        return super().dispatch(*args, **kwargs)


class DraftVersionMixin:
    """Fetch the version object which is being edited as a draft."""

    def dispatch(self, *args, **kwargs):
        self.version = self.extension.versions.first()
        return super().dispatch(*args, **kwargs)

extensions/views/submit.py
import logging

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.views.generic.edit import CreateView

from extensions.models import Version, Extension
from files.forms import FileForm
from files.models import File

logger = logging.getLogger(__name__)


class UploadFileView(LoginRequiredMixin, CreateView):
    model = File
    template_name = 'extensions/submit.html'
    form_class = FileForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        drafts = Extension.objects.authored_by(self.request.user).filter(
            status=Extension.STATUSES.DRAFT
        )
        context['drafts'] = drafts
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def get_success_url(self):
        return self.extension.get_draft_url()

    @transaction.atomic
    def form_valid(self, form):
        """Create an extension and a version already, associated with the user."""
        self.file = form.instance

        parsed_extension_fields = self.file.parsed_extension_fields
        if parsed_extension_fields:
            # Try to look up extension by the same author and file info
            extension = (
                Extension.objects.authored_by(self.request.user)
                .filter(type=self.file.type, **parsed_extension_fields)
                .first()
            )
            if extension:
                logger.warning(
                    'Found existing extension pk=%s for file pk=%s',
                    extension.pk,
                    self.file.pk,
                )
                return False

        # Make sure an extension has a user associated to it from the beginning, otherwise
        # it will prevent it from being re-uploaded and yet not show on My Extensions.
        self.extension = Extension.objects.update_or_create(
            type=self.file.type, **parsed_extension_fields
        )[0]
        self.extension.authors.add(self.request.user)
        self.extension.save()

        # Need to save the form to be able to use the file to create the version.
        self.object = self.file = form.save()

        Version.objects.update_or_create(
            extension=self.extension, file=self.file, **self.file.parsed_version_fields
        )[0]

        return super().form_valid(form)

extensions/templates/extensions/components/authors.html
{# Indentation looks like this so there is no gap between the author name and comma. #}
{% for author in extension.authors.all %}{% if forloop.counter > 1 %},&nbsp;{% endif %}<a class="d-inline" href="{% url "extensions:by-author" user_id=author.pk %}" title="{{ author }}">{{ author }}</a>{% endfor %}

extensions/templates/extensions/components/badge_tag.html
{% load extensions %}

<a href="{% url "extensions:by-tag" tag_slug=tag.slug %}" title="{{ tag.name }}"
  class="badge badge-tag {{ classes }}">
  {{ tag.name }}
</a>

extensions/templates/extensions/components/blender_version.html
{% load i18n common %}

<a
  href="https://www.blender.org/download/releases/{{ version.blender_version_min|version_without_patch|replace:".,-" }}/"
  title="{{ version.blender_version_min }}">Blender {{ version.blender_version_min|version_without_patch }}</a>
{% if is_editable %}
    <span class="me-2">&mdash;</span>
    <input name="blender_version_max" class="form-control"
      value="{{version.blender_version_max|default_if_none:''}}"
      placeholder="{% trans 'max. Blender version' %}"
      pattern="^([0-9]+\.[0-9]+\.[0-9]+)?$"
      title="{% trans 'Blender version, e.g. 4.1.0' %}"
    />
    {% for error in form.errors.blender_version_max %}
      <div class="error">{{ error }}</div>
    {% endfor %}
{% else %}
  {% if version.blender_version_max %}
  {% if version.blender_version_max|version_without_patch != version.blender_version_min|version_without_patch %}
    &mdash;
    <a
      href="https://www.blender.org/download/releases/{{ version.blender_version_max|version_without_patch|replace:".,-" }}/"
      title="{{ version.blender_version_max }}">{{ version.blender_version_max|version_without_patch }}</a>
    {% endif %}
  {% else %}
    &nbsp;{% trans 'and newer' %}
  {% endif %}
  <a href="{{ version.extension.get_review_url }}?report_compatibility_issue&version={{ version.version }}#id_message" title="{% trans 'Report compatibility issue' %}"><i class="i-flag"></i></a>
{% endif %}

extensions/templates/extensions/components/card.html
{% load common filters static %}
{% with latest=extension.latest_version type_display=extension.get_type_display %}
  <div class="cards-item">
    <div class="cards-item-content">
      <a href="{{ extension.get_detail_url }}">
        {% with featured_image=extension.featured_image.thumbnail_360p_url %}
          <div class="cards-item-thumbnail">
            {% if featured_image %}
              <img alt="{{ extension.name }}" src="{{ featured_image }}" title="{{ extension.name }}">
            {% else %}
              {% include "extensions/components/extension_type_icon.html" with type=extension.type %}
            {% endif %}
          </div>
        {% endwith %}
      </a>
      <div class="cards-item-headline">
        {{ type_display }}
      </div>
      <h3 class="cards-item-title">
        <a href="{{ extension.get_detail_url }}">{{ extension.name }}</a>
      </h3>
      <div class="cards-item-excerpt">
        <p>
          {{ latest.tagline }}
        </p>
      </div>
      <div class="cards-item-extra">
        {% if latest.tags.count %}
        <ul class="flex-wrap mb-1">
          {% for tag in latest.tags.all %}
            <li class="mb-1">
              {% include "extensions/components/badge_tag.html" with version=latest classes="badge-sm" %}
            </li>
          {% endfor %}
        </ul>
        {% endif %}

        <ul>
          <li>
          {% if extension.team %}
            {% with team=extension.team %}
            <a href="{{ team.get_absolute_url }}" title="{{ team.name }}">{{ team.name }}</a>
            {% endwith %}
          {% elif extension.authors.count %}
            {% include "extensions/components/authors.html" %}
          {% endif %}
          </li>
        </ul>

        <ul class="cards-item-extra-rating-stars">
          {% if extension.average_score %}
          <li class="me-auto">
            <a class="align-items-center d-flex" href="{{ extension.get_ratings_url }}">
            {% include "ratings/components/average.html" with score=extension.average_score %}
            ({{ extension.text_ratings_count|int_compact }})
            </a>
          </li>
          {% endif %}

          {% if show_type %}
          <li>
            {{ type_display }}
          </li>
          {% endif %}

          {% if extension.download_count %}
          <li title="{{ extension.download_count }} downloads">
            <i class="i-download"></i> {{ extension.download_count | int_compact }}
          </li>
          {% endif %}
        </ul>
      </div>
      {# Author/admin tools can be added here in an extending template #}
      {% block admin %}{% endblock admin %}
    </div>
  </div>
{% endwith %}

extensions/templates/extensions/components/categories.html
{% load i18n %}
<div class="card p-3 mb-3">
  <div class="card-header mx-3">
    <h2 class="card-title">{% trans 'Categories' %}</h2>
  </div>
  <div class="card-body m-3">
    <div class="card-text text-center">
      {% for category in categories %}
        {% include "extensions/components/category.html" %}
      {% endfor %}
    </div>
  </div>
</div>

extensions/templates/extensions/components/detail_card_version_permissions.html
<div class="ext-detail-permissions">
  <dt>Permissions</dt>
  {% if permissions %}
  <dd>This version requests the following:
  <ul>
    {% for p in permissions %}
    <li>
      <div>
        <i class="i-permission-{{ p.slug }}"></i>
      </div>
      <div>
        <strong>{{ p.name }}</strong>
        <small>{{ p.reason }}</small>
      </div>
    </li>
    {% endfor %}
  </ul>
  </dd>
  {% else %}
  <dd>No special permissions required.</dd>
  {% endif %}
</div>

extensions/templates/extensions/components/dropdown_admin.html
{% load i18n %}

<li>
  <a href="{% url 'admin:extensions_extension_change' extension.pk %}" class="dropdown-item is-admin">
    <i class="i-edit"></i> {% trans 'Extension' %}
  </a>
</li>

{% if extension.latest_version %}
<li>
  <a href="{% url 'admin:extensions_version_change' extension.latest_version.pk %}" class="dropdown-item is-admin">
    <i class="i-puzzle"></i> {% trans 'Version' %}
  </a>
</li>
{% endif %}

<li>
  <a href="{% url 'admin:ratings_rating_changelist' %}?extension_id={{ extension.pk }}" class="dropdown-item is-admin">
    <i class="i-star"></i> {% trans 'Ratings' %}
  </a>
</li>

{% if not '/approval-queue/' in request.get_full_path %}
<li>
  <a href="{{ extension.get_review_url }}" class="dropdown-item is-admin">
    <i class="i-eye"></i> {% trans 'View in Approval Queue' %}
  </a>
</li>
{% endif %}

{% if extension.authors.all.0 %}
<li class="dropdown-divider"></li>
<li>
  <a href="{% url 'admin:users_user_change' extension.authors.all.0.pk %}" class="dropdown-item is-admin">
    <i class="i-user"></i> {% trans 'Maintainer' %}{{ extension.authors.all.count|pluralize }}
    {% if extension.authors.all.count > 1 %}({{ extension.authors.all.count }}){% endif %}
  </a>
</li>
{% endif %}
{% if extension.team %}
<li>
  <a href="{% url 'admin:teams_team_change' extension.team.pk %}" class="dropdown-item is-admin">
    <i class="i-users"></i> {% trans 'Team' %}
  </a>
</li>
{% endif %}

extensions/templates/extensions/components/extension_edit_detail_card.html
{% load i18n common %}

{# Info Summary #}
<section class="ext-detail-info">
  <div class="card p-0">
    {% if is_initial %}
    <div class="badge badge-card badge-info">
      Information retrieved from manifest
    </div>
    {% else %}
    <div class="dl-row px-3 pt-3">
      <div class="dl-col mb-0">
        <dt>{% trans 'Approval Status' %}</dt>
        <dd>{% include "common/components/status.html" with object=extension %}</dd>
      </div>
    </div>
    {% endif %}
    <div class="p-3">
      <dl>
        {% if extension.team or extension.authors.count %}
        <div class="dl-row">
          <div class="dl-col">
          {% if extension.team %}
          {% with team=extension.team %}
          <dt>{% trans 'Team' %}</dt>
          <dd>
            <a href="{{ team.get_absolute_url }}" title="{{ team.name }}">{{ team.name }}</a>
          </dd>
          {% endwith %}
          {% elif extension.authors.count %}
          <dt>Developer{{ extension.authors.count|pluralize }}</dt>
          <dd class="ext-detail-info-authors">
            {% include "extensions/components/authors.html" %}
          </dd>
          {% endif %}
          </div>
        </div>
        {% endif %}

        <div class="dl-row">
          <div class="dl-col">
            <dt>{% trans 'Name' %}</dt>
            <dd>{{ extension.name }}</dd>
          </div>
        </div>

        <div class="dl-row">
          <div class="dl-col">
            <dt>{% trans 'ID' %}</dt>
            <dd>{{ extension.extension_id }}</dd>
          </div>
        </div>

        <div class="dl-row">
          <div class="dl-col">
            <dt>{% trans 'Tagline' %}</dt>
            <dd title="{{ version.tagline }}">{{ version.tagline }}</dd>
          </div>
        </div>

        <div class="dl-row">
          <div class="dl-col">
            <dt>{% trans 'Version' %}</dt>
            <dd>
              <a href="{{ extension.get_versions_url }}">
              {{ version.version }}
              </a>
            </dd>
          </div>
          <div class="dl-col">
            <dt>{% trans 'Size' %}</dt>
            <dd>{{ version.file.size_bytes|filesizeformat }}</dd>
          </div>
        </div>

        <div class="dl-row">
          <div class="dl-col">
            <dt>{% trans 'Compatibility' %}</dt>
            <dd class="align-items-center d-flex">
              {% include "extensions/components/blender_version.html" with version=version is_editable=is_editable form=form %}
            </dd>
          </div>
        </div>

        {% if extension.website %}
        <div class="dl-row">
          <div class="dl-col">
            <dt>{% trans 'Website' %}</dt>
            <dd>{% include "common/components/external_link.html" with url=extension.website show_path=True %}</dd>
          </div>
        </div>
        {% endif %}

        <div class="dl-row">
          <div class="dl-col">
            <dt>License{{ version.licenses.count|pluralize }}</dt>
            {% for license in version.licenses.all %}
            <dd>
              {% include "common/components/external_link.html" with url=license.url title=license %}
            </dd>
            {% endfor %}
          </div>
        </div>

        <div class="dl-row">
          <div class="dl-col">
            {% include "extensions/components/detail_card_version_permissions.html" with permissions=version.permissions_with_reasons %}
          </div>
        </div>

        <div class="dl-row">
          <dd class="ext-detail-info-tags">
            {% if version.tags.count %}
              {% include "extensions/components/tags.html" with version=version %}
            {% else %}
              No tags.
            {% endif %}
          </dd>
        </div>
      </dl>
    </div>
  </div>
</section>

extensions/templates/extensions/components/extension_form.html
{% if user in extension.authors.all and user.teams.count > 0 %}
<div class="row mb-3">
  <div class="col">
  {# django won't allow submitting an empty field for a required field, so using a hack with an explicit required=True #}
  {% include "common/components/field.html" with field=extension_form.team label="Assign Team" required=True %}
  </div>
</div>
{% endif %}

<div>
{% include "common/components/field.html" with field=extension_form.description label="Description" placeholder="Describe the extension..." %}
</div>

<div>
{% include "common/components/field.html" with field=extension_form.support placeholder="https://example.com" %}
</div>

extensions/templates/extensions/components/galleria.html
{% with preview_count=previews|length %}
  <section class="galleria-container" id="galleria-container">
    {% if previews %}
      <div class="galleria-items{% if preview_count > 5 %} is-many{% endif %}{% if preview_count == 1 %} is-single{% endif %}" id="galleria-items">
        {% for preview in previews %}
          {% with thumbnail_1080p_url=preview.file.thumbnail_1080p_url file=preview.file %}
          {% with thumbnail_360p_url=preview.file.thumbnail_360p_url file=preview.file %}
            <a
              class="galleria-item js-galleria-item-preview galleria-item-type-{{ file.content_type|slugify|slice:5 }}{% if forloop.first %} is-active{% endif %}"
              href="{{ thumbnail_1080p_url }}"
              {% if 'video' in file.content_type %}data-galleria-video-url="{{ file.source.url }}"{% endif %}
              data-galleria-content-type="{{ file.content_type }}"
              data-galleria-index="{{ forloop.counter }}">

              <img src="{{ thumbnail_360p_url }}" alt="{{ preview.caption }}">
            </a>
          {% endwith %}
          {% endwith %}
        {% endfor %}
      </div>
    {% else %}
      <div class="galleria-item is-empty">
        <div>
          No preview yet.
          {% if is_maintainer %}
            <a class="btn btn-primary px-5" href="{{ extension.get_manage_url }}#previews">Add a Preview</a>
          {% endif %}
        </div>
      </div>
    {% endif %}
  </section>
{% endwith %}

extensions/templates/extensions/components/icon.html
{% load static %}

<div class="extension-icon {{ classes}}">
  <img alt="{{ extension.get_type_display }} {{ extension.name }}" src="{% if extension.icon.source %}{{ extension.icon.source.url }}{% else %}{% static 'common/images/no-icon.png' %}{% endif %}">
</div>

extensions/templates/extensions/components/platforms.html
{% if version.platforms.all %}
<div>
  Supported platforms:
  <ul>
  {% for p in version.platforms.all %}
    <li>{{p.name}}</li>
  {% endfor %}
  </ul>
</div>
{% endif %}

extensions/templates/extensions/components/tags.html
{% for tag in version.tags.all %}
{% include "extensions/components/badge_tag.html" %}
{% endfor %}