abuse/urls.py
from django.urls import path, re_path, include

from . import views
from constants.base import EXTENSION_SLUGS_PATH

app_name = 'abuse'
urlpatterns = [
    path('abuse/reports/', views.ReportList.as_view(), name='report-list'),
    path('abuse/reports/<int:pk>/', views.ReportView.as_view(), name='view-report'),
    re_path(
        rf'^(?P<type_slug>{EXTENSION_SLUGS_PATH})/',
        include(
            [
                path(
                    '<slug:slug>/report/',
                    views.ReportExtensionView.as_view(),
                    name='report-extension',
                ),
                path(
                    '<slug:slug>/<str:version>/<int:rating>/report/',
                    views.ReportRatingView.as_view(),
                    name='report-ratings',
                ),
            ],
        ),
    ),
    # TODO: report user view and URL
]

blender_extensions/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.flatpages import views as flatpages_views
from django.urls import path, include, re_path
from django.views.static import serve
from django.views.generic.base import RedirectView

from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

import blender_id_oauth_client.urls

import common.views.errors

admin.site.enable_nav_sidebar = False
admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    path('oauth/', include(blender_id_oauth_client.urls)),
    path('admin/', include('loginas.urls')),
    path('admin/', admin.site.urls),
    path('', include('ratings.urls')),
    path('', include('extensions.urls')),
    path('', include('abuse.urls')),
    path('', include('users.urls')),
    path('', include('teams.urls')),
    path('', include('reviewers.urls')),
    path('', include('notifications.urls')),
    path('', include('apitokens.urls')),
    path('api/swagger/', RedirectView.as_view(url='/api/v1/swagger/')),
    path('api/v1/', SpectacularAPIView.as_view(), name='schema_v1'),
    path('api/v1/swagger/', SpectacularSwaggerView.as_view(url_name='schema_v1'), name='swagger'),
    # Flatpages
    path('about/', flatpages_views.flatpage, {'url': '/about/'}, name='flatpage-about'),
    re_path(r'^(?P<url>.*/)$', flatpages_views.flatpage),
]
handler400 = common.views.errors.ErrorView.as_view(status=400)
handler403 = common.views.errors.ErrorView.as_view(status=403)
handler404 = common.views.errors.ErrorView.as_view(status=404)
handler500 = common.views.errors.ErrorView.as_view(status=500)

if settings.DEBUG:
    urlpatterns = [
        re_path(
            r'^media/(?P<path>.*)$',
            serve,
            {
                'document_root': settings.MEDIA_ROOT,
            },
        ),
        path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns

extensions/urls.py
from django.urls import path, re_path, include, reverse_lazy
from django.views.generic import RedirectView

from constants.base import EXTENSION_SLUGS_PATH
from extensions.views import api, public, submit, manage

app_name = 'extensions'
urlpatterns = [
    path('submit/', submit.UploadFileView.as_view(), name='submit'),
    # TODO: move /accounts pages under its own app when User model is replaced
    path('accounts/extensions/', manage.ManageListView.as_view(), name='manage-list'),
    # FIXME: while there's no profile page, redirect to My Extensions instead
    path(
        'accounts/profile/',
        RedirectView.as_view(url=reverse_lazy('extensions:manage-list'), permanent=False),
    ),
    # API
    path('api/v1/extensions/', api.ExtensionsAPIView.as_view(), name='api'),
    path(
        'api/v1/extensions/<str:extension_id>/versions/new/',
        api.UploadExtensionVersionView.as_view(),
        name='upload-extension-version',
    ),
    # Public pages
    path('', public.HomeView.as_view(), name='home'),
    path('search/', public.SearchView.as_view(), name='search'),
    path('author/<int:user_id>/', public.SearchView.as_view(), name='by-author'),
    path('search/', public.SearchView.as_view(), name='search'),
    path('tag/<slug:tag_slug>/', public.SearchView.as_view(), name='by-tag'),
    path('team/<slug:team_slug>/', public.SearchView.as_view(), name='by-team'),
    re_path(
        rf'^(?P<type_slug>{EXTENSION_SLUGS_PATH})/',
        include(
            [
                path('<slug:slug>/', public.ExtensionDetailView.as_view(), name='detail'),
            ]
        ),
    ),
    re_path(
        rf'^(?P<type_slug>{EXTENSION_SLUGS_PATH})/$',
        public.SearchView.as_view(),
        name='by-type',
    ),
    # Pages for maintainers
    re_path(
        rf'^(?P<type_slug>{EXTENSION_SLUGS_PATH})/',
        include(
            [
                path(
                    '<slug:slug>/draft/',
                    manage.DraftExtensionView.as_view(),
                    name='draft',
                ),
                path(
                    '<slug:slug>/manage/',
                    manage.UpdateExtensionView.as_view(),
                    name='manage',
                ),
                path(
                    '<slug:slug>/delete/',
                    manage.DeleteExtensionView.as_view(),
                    name='delete',
                ),
                path(
                    '<slug:slug>/manage/versions/',
                    manage.ManageVersionsView.as_view(),
                    name='manage-versions',
                ),
                path(
                    '<slug:slug>/manage/versions/new/',
                    manage.NewVersionView.as_view(),
                    name='new-version',
                ),
                path(
                    '<slug:slug>/manage/versions/new/<int:pk>/',
                    manage.NewVersionFinalizeView.as_view(),
                    name='new-version-finalise',
                ),
                path(
                    '<slug:slug>/manage/versions/<int:pk>/delete/',
                    manage.VersionDeleteView.as_view(),
                    name='version-delete',
                ),
                path(
                    '<slug:slug>/manage/versions/<int:pk>/update/',
                    manage.UpdateVersionView.as_view(),
                    name='version-update',
                ),
                path(
                    '<slug:slug>/<version>/download/<filename>',
                    public.extension_version_download,
                    name='version-download',
                ),
                path('<slug:slug>/versions/', manage.VersionsView.as_view(), name='versions'),
            ],
        ),
    ),
]

notifications/urls.py
from django.urls import path, include

import notifications.views as views

app_name = 'notifications'
urlpatterns = [
    path(
        'notifications/',
        include(
            [
                path('', views.NotificationsView.as_view(), name='notifications'),
                path(
                    'mark-read-all/',
                    views.MarkReadAllView.as_view(),
                    name='notifications-mark-read-all',
                ),
                path(
                    '<int:pk>/mark-read/',
                    views.MarkReadView.as_view(),
                    name='notifications-mark-read',
                ),
            ],
        ),
    ),
]

notifications/models.py
import logging

from actstream.models import Action
from django.contrib.auth import get_user_model
from django.db import models
from django.template import loader, TemplateDoesNotExist

from constants.activity import Verb
from utils import absolutify

User = get_user_model()
logger = logging.getLogger(__name__)


class Notification(models.Model):
    """Notification records are created in Action's post_save signal.
    When a user marks a notification as read, read_at is set.
    send_notification_emails management command runs periodically in background and sends all
    notifications that haven't been processed yet, read_at is not checked when sending emails.
    email_sent flag is used only to record the fact that we attempted to send an email.
    A user can unsubscribe from notification emails in their profile settings.
    """

    recipient = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    action = models.ForeignKey(Action, null=False, on_delete=models.CASCADE)
    email_sent = models.BooleanField(default=False, null=False)
    processed_by_mailer_at = models.DateTimeField(default=None, null=True)
    read_at = models.DateTimeField(default=None, null=True)

    class Meta:
        indexes = [
            models.Index(fields=['processed_by_mailer_at']),
            models.Index(fields=['recipient', 'read_at']),
        ]
        unique_together = ['recipient', 'action']

    @property
    def original_template_name(self) -> str:
        """Template name constructed from action type, target and so on.

        If we want to override email template for this specific notification,
        this is the name of the template that should be created.
        """
        action = self.action
        action_object = action.action_object
        target_name = action.target.__class__.__name__.lower()
        action_object_name = action_object.__class__.__name__.lower() if action_object else ''
        return f"new_activity_{action_object_name}_{target_name}_{action.verb.replace(' ', '_')}"

    @property
    def template_name(self) -> str:
        """Template name to be used for constructing notification email."""
        default_name = 'new_activity'
        name = self.original_template_name
        args = {'name': name, 'default_name': default_name}

        try:
            loader.get_template(f'emails/{name}.html')
        except TemplateDoesNotExist:
            logger.warning('Template %(name)s does not exist, using %(default_name)s', args)
            return default_name
        return name

    def get_template_context(self):
        """Return template context to be used in the notification email."""
        action = self.action
        action_object = action.action_object
        quoted_message = getattr(action_object, 'message', getattr(action_object, 'text', ''))
        context = {
            'Verb': Verb,
            'action': action,
            'action_object': action_object,
            'notification': self,
            'quoted_message': quoted_message,
            'target': action.target,
            'url': self.get_absolute_url(),
            'user': self.recipient,
        }
        return context

    def get_absolute_url(self):
        if self.action.verb == Verb.RATED_EXTENSION:
            fragment = f'#review-{self.action.action_object.pk}'
            url = self.action.target.get_ratings_url() + fragment
        elif self.action.verb in [
            Verb.APPROVED,
            Verb.COMMENTED,
            Verb.REQUESTED_CHANGES,
            Verb.REQUESTED_REVIEW,
        ]:
            fragment = f'#activity-{self.action.action_object.pk}'
            url = self.action.target.get_review_url() + fragment
        elif self.action.action_object is not None:
            url = self.action.action_object.get_absolute_url()
        else:
            url = self.action.target.get_absolute_url()

        # TODO? url cloacking to mark visited notifications as read automatically
        return absolutify(url)

notifications/views.py
"""Notifications pages."""
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden
from django.shortcuts import redirect
from django.utils import timezone
from django.views.generic import ListView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import FormView
from django.views import View

from notifications.models import Notification


class NotificationsView(LoginRequiredMixin, ListView):
    model = Notification
    paginate_by = 20

    def get_queryset(self):
        return (
            Notification.objects.filter(recipient=self.request.user)
            .select_related('action')
            .prefetch_related('action__action_object', 'action__actor', 'action__target')
            .order_by('-id')
        )


class MarkReadAllView(LoginRequiredMixin, FormView):
    model = Notification
    raise_exception = True

    def post(self, request, *args, **kwargs):
        """Mark all previously unread notifications as read."""
        unread = self.model.objects.filter(recipient=request.user, read_at__isnull=True)
        now = timezone.now()
        for notification in unread:
            notification.read_at = now

        Notification.objects.bulk_update(unread, ['read_at'])
        return redirect('notifications:notifications')


class MarkReadView(LoginRequiredMixin, SingleObjectMixin, View):
    model = Notification
    raise_exception = True

    def post(self, request, *args, **kwargs):
        notification = self.get_object()
        if notification.recipient != request.user:
            return HttpResponseForbidden()
        notification.read_at = timezone.now()
        notification.save(update_fields=['read_at'])
        return redirect('notifications:notifications')

notifications/templates/notifications/notification_list.html
{% extends "common/base.html" %}
{% load common filters i18n %}

{% block page_title %}{% blocktranslate %}Notifications{% endblocktranslate %}{% endblock page_title %}

{% block content %}
  <h1>{% trans 'Notifications' %}</h1>


  {% if notification_list %}
    <div class="notifications">
      {% if user|unread_notification_count %}
        <form action="{% url 'notifications:notifications-mark-read-all' %}" method="post">
          {% csrf_token %}
          <button class="btn mb-3" type="submit"><i class="i-eye"></i> {% trans 'Mark All as Read' %}</button>
        </form>
      {% endif %}
      <div class="box">
        <table class="notifications-list">
          <tbody>
            {% for notification in notification_list %}
              <tr class="notifications-item {% if notification.read_at%}is-read{% endif %}">
                <td class="notifications-item-time">
                  {{ notification.action.timestamp | naturaltime_compact }}
                </td>
                <td class="notifications-item-content">
                  {# TODO: @back-end add link to action target ID (so that link works as an anchor link) #}
                  <a href="{{ notification.get_absolute_url }}"><span class="me-2">{{ notification.action.actor }} {{ notification.action.verb }} {{ notification.action.target }}</span><span class="notifications-item-dot"></span></a>
                </td>
                <td class="notifications-item-nav">
                  <div class="dropdown">
                    <button class="btn btn-link dropdown-toggle js-dropdown-toggle px-0" data-toggle-menu-id="js-notifications-item-nav-{{ notification.id }}">
                      <i class="i-more-vertical"></i>
                    </button>
                    <ul class="dropdown-menu dropdown-menu-right js-dropdown-menu" id="js-notifications-item-nav-{{ notification.id }}">
                      <li class="nav-item-mark-as-read">
                        <form action="{% url 'notifications:notifications-mark-read' pk=notification.pk %}" method="post">
                          {% csrf_token %}
                          <button class="dropdown-item" title="Mark as Read" type="submit"><i class="i-eye"></i> Mark as Read </button>
                        </form>
                      </li>
                      {# TODO: add feature 'Mark as Unread' (optional) #}
                      {% comment %}
                        <li class="nav-item-mark-as-unread">
                          <form>
                            <button class="dropdown-item" title="Mark as Unread" type="submit"><i class="i-eye-off"></i> Mark as Unread </button>
                          </form>
                        </li>
                      {% endcomment %}
                      <li>
                        <a class="dropdown-item" href="{% url 'extensions:by-author' user_id=notification.action.actor.pk %}"><i class="i-user"></i> View User</a>
                      </li>
                    </ul>
                  </div>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  {% else %}
    <p>
      {% trans 'You have no notifications' %}
    </p>
  {% endif %}

  {{ page_obj|paginator }}
{% endblock content %}